### ISSUE TITLE
RenderTextureに深度バッファを書き込めていない

### ISSUE THREAD

**Issue by Nattuhan** [haw2fregel/OverdrawChecker#1]
不透明なもので半透明なものを覆うように表示したところ、深度テストによって隠されませんでした。

以下のRenderTexutureを作成している箇所で、

https://github.com/haw2fregel/OverdrawChecker/blob/2d7fc7bc4c3bd56bb3942a3b28ca12ca648a9d22/Assets/OverdrawChecker/Script/OverdrawChecker.cs#L43

深度バッファを書き込むことにより正しく深度テストが行われると思います

`_rt = new RenderTexture(_screenRes.x, _screenRes.y, 16, RenderTextureFormat.RFloat);`

https://docs.unity3d.com/ja/2019.4/ScriptReference/RenderTexture-depth.html

**Comment by haw2fregel** [comment]
こちら確認できたので、修正いたしました。
ご指摘ありがとうございます！
